### ISSUE TITLE
Reuse git commit template file

### ISSUE THREAD

**Issue by vlaw** [myheritage/intellij-commit-message-template-plugin#3]
This plugin is very useful.

It would be great ,if this plugin offer an option to specify a template file, so people can use the `commit.template` file both in command and IDE.

**Comment by gorenm** [comment]
Great idea.
Working on it.

**Comment by gorenm** [comment]
Closed with the latest [commit](https://github.com/myheritage/intellij-commit-message-template-plugin/commit/7f8bdbd2a2feb2e3c853ba9f726180627cc21268).
